/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Beans.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Terminal
 */
public class frmMenuPrincipalDiretor extends javax.swing.JFrame {

    public Usuario user;

    public frmMenuPrincipalDiretor(Usuario user2) {
        initComponents();
        this.user = user2;
        mudaLabel(user2.getNome());
    }

    frmMenuPrincipalDiretor() {
    }

    public void mudaLabel(String nome) {
        jLabel2.setText("Bem Vindo(a), Diretor(a) " + nome +".");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnCadastroGeral = new javax.swing.JButton();
        btnAprovacaoAvaliacaoBimestral = new javax.swing.JButton();
        btnCadastroClasse = new javax.swing.JButton();
        btnAprovacaoAvaliacaoMensal = new javax.swing.JButton();
        btnAprovacaoAulaSemanal2 = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        btnCadastroAluno1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Formulário Principal Diretor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Menu Principal Diretor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 255, 31);

        jLabel2.setText("Bem Vindo(a), Diretor(a):");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 390, 14);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(400, 10, 780, 620);

        btnInicio.setText("Início");
        btnInicio.setPreferredSize(new java.awt.Dimension(197, 23));
        getContentPane().add(btnInicio);
        btnInicio.setBounds(190, 140, 211, 23);

        btnCadastroGeral.setText("Cadastro Geral");
        btnCadastroGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroGeralActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroGeral);
        btnCadastroGeral.setBounds(190, 170, 211, 23);

        btnAprovacaoAvaliacaoBimestral.setText("Aprovação de Avaliação Bimestrall");
        getContentPane().add(btnAprovacaoAvaliacaoBimestral);
        btnAprovacaoAvaliacaoBimestral.setBounds(190, 320, 211, 23);

        btnCadastroClasse.setText("Cadastro de Classe");
        btnCadastroClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClasseActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroClasse);
        btnCadastroClasse.setBounds(190, 230, 211, 23);

        btnAprovacaoAvaliacaoMensal.setText("Aprovação de Avaliação Mensal");
        getContentPane().add(btnAprovacaoAvaliacaoMensal);
        btnAprovacaoAvaliacaoMensal.setBounds(190, 290, 211, 23);

        btnAprovacaoAulaSemanal2.setText("Aprovação de Plano de Aula Semanal");
        getContentPane().add(btnAprovacaoAulaSemanal2);
        btnAprovacaoAulaSemanal2.setBounds(190, 260, 211, 23);
        getContentPane().add(jCalendar1);
        jCalendar1.setBounds(-1, 355, 330, 220);

        btnCadastroAluno1.setText("Cadastro de Aluno");
        btnCadastroAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroAluno1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroAluno1);
        btnCadastroAluno1.setBounds(190, 200, 211, 23);

        btnSair.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(10, 595, 53, 25);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 34, 14);

        setSize(new java.awt.Dimension(1204, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int dialogResult;
        dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja sair?", "Aviso!", 1);
        if (dialogResult == JOptionPane.YES_OPTION) {
             FrmLogin login = new FrmLogin();
             login.setVisible(true);
             this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCadastroGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroGeralActionPerformed
        FrmCadastroGeral cadastrogeral = new FrmCadastroGeral();
        cadastrogeral.setVisible(true);
    }//GEN-LAST:event_btnCadastroGeralActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastroAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroAluno1ActionPerformed
        // TODO add your handling code here:
        FrmCadastroAluno aluno = new FrmCadastroAluno();
        aluno.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnCadastroAluno1ActionPerformed

    private void btnCadastroClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClasseActionPerformed
        // TODO add your handling code here:
        FrmCadastroClasse classe = new FrmCadastroClasse();
        classe.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnCadastroClasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipalDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipalDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipalDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipalDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipalDiretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprovacaoAulaSemanal2;
    private javax.swing.JButton btnAprovacaoAvaliacaoBimestral;
    private javax.swing.JButton btnAprovacaoAvaliacaoMensal;
    private javax.swing.JButton btnCadastroAluno1;
    private javax.swing.JButton btnCadastroClasse;
    private javax.swing.JButton btnCadastroGeral;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSair;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
